# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            kristopher.io
tagline:          'ツ'
description:      ''
url:              https://kristopher.io

author:
  name:           'Kristopher Williams'
  url:            https://twitter.com/southpawlife

paginate:         5

# Custom vars
version:          2.0.1
excerpt_separator: <!--more-->
github:
  repo:           https://github.com/southpawlife

plugins: [jekyll-paginate]

theme: jekyll-theme-hacker